
#ifndef __PERIP_H
#define __PERIP_H

#include <msp430.h>

//#include "hw_obj.h"

//////////////uart////////////////////
#define	_PERIP_UART_CNT	2

#define _PERIP_UART0_XD_PORT_SEL_ADDR	&P3SEL
#define _PERIP_UART0_XD_PORT_SEL2_ADDR	NULL_ADDR

#define _PERIP_UART0_TXD	BIT3
#define _PERIP_UART0_RXD	BIT4


#define _PERIP_UART0_CTL0_ADDR	&UCA0CTL0
#define _PERIP_UART0_CTL1_ADDR	&UCA0CTL1
#define _PERIP_UART0_BR0_ADDR	&UCA0BR0
#define _PERIP_UART0_BR1_ADDR	&UCA0BR1
#define _PERIP_UART0_MCTL_ADDR	&UCA0MCTL

#define _PERIP_UART0_IE_ADDR	&UCA0IE
#define _PERIP_UART0_IFG_ADDR	&UCA0IFG

#define _PERIP_UART0_RXIE	UCRXIE
#define _PERIP_UART0_TXIFG	UCTXIFG
#define _PERIP_UART0_RXIFG	UCRXIFG

#define _PERIP_UART0_TXBUF_ADDR	&UCA0TXBUF
#define _PERIP_UART0_RXBUF_ADDR	&UCA0RXBUF

#define _PERIP_UART0_ISR_VECTOR	USCI_A0_VECTOR


#define _PERIP_UART1_XD_PORT_SEL_ADDR	&P4SEL
#define _PERIP_UART1_XD_PORT_SEL2_ADDR	NULL_ADDR

#define _PERIP_UART1_TXD	BIT4
#define _PERIP_UART1_RXD	BIT5


#define _PERIP_UART1_CTL0_ADDR	&UCA1CTL0
#define _PERIP_UART1_CTL1_ADDR	&UCA1CTL1
#define _PERIP_UART1_BR0_ADDR	&UCA1BR0
#define _PERIP_UART1_BR1_ADDR	&UCA1BR1
#define _PERIP_UART1_MCTL_ADDR	&UCA1MCTL

#define _PERIP_UART1_IE_ADDR	&UCA1IE
#define _PERIP_UART1_IFG_ADDR	&UCA1IFG

#define _PERIP_UART1_RXIE	UCRXIE
#define _PERIP_UART1_TXIFG	UCTXIFG
#define _PERIP_UART1_RXIFG	UCRXIFG

#define _PERIP_UART1_TXBUF_ADDR	&UCA1TXBUF
#define _PERIP_UART1_RXBUF_ADDR	&UCA1RXBUF

#define _PERIP_UART1_ISR_VECTOR	USCI_A1_VECTOR



// #define	_PERIP_PWM0_CTL	TACTL_
// #define	_PERIP_PWM0_CCTL0	CCTL0_
// #define	_PERIP_PWM0_CCTL1	CCTL1_
// #define	_PERIP_PWM0_CCTL2	CCTL2_
// 
// #define	_PERIP_PWM0_CCR0	CCR0_
// #define	_PERIP_PWM0_CCR1	CCR1_
// #define	_PERIP_PWM0_CCR2	CCR2_


/////////////////i2c//////////////////////
#define _PERIP_I2C0_XD_PORT_SEL_ADDR	&P3SEL
#define _PERIP_I2C0_XD_PORT_SEL2_ADDR	NULL_ADDR

#define _PERIP_I2C0_SCL	BIT1
#define _PERIP_I2C0_SDA	BIT0


#define _PERIP_I2C0_CTL0_ADDR	&UCB0CTL0
#define _PERIP_I2C0_CTL1_ADDR	&UCB0CTL1
#define _PERIP_I2C0_BR0_ADDR	&UCB0BR0
#define _PERIP_I2C0_BR1_ADDR	&UCB0BR1

#define _PERIP_I2C0_IE_ADDR	&UCB0IE
#define _PERIP_I2C0_IFG_ADDR	&UCB0IFG
#define _PERIP_I2C0_STAT_ADDR	&UCB0STAT


#define _PERIP_I2C0_OA_ADDR &UCB0I2COA
#define _PERIP_I2C0_SA_ADDR &UCB0I2CSA

#define _PERIP_I2C0_RXIE	UCRXIE
#define _PERIP_I2C0_TXIFG	UCTXIFG
#define _PERIP_I2C0_RXIFG	UCRXIFG

#define _PERIP_I2C0_TXBUF_ADDR	&UCB0TXBUF
#define _PERIP_I2C0_RXBUF_ADDR	&UCB0RXBUF

#define _PERIP_I2C0_ISR_VECTOR	USCI_B0_VECTOR


#define _PERIP_I2C1_XD_PORT_SEL_ADDR	&P4SEL
#define _PERIP_I2C1_XD_PORT_SEL2_ADDR	NULL_ADDR

#define _PERIP_I2C1_SCL	BIT2
#define _PERIP_I2C1_SDA	BIT1


#define _PERIP_I2C1_CTL0_ADDR	&UCB1CTL0
#define _PERIP_I2C1_CTL1_ADDR	&UCB1CTL1
#define _PERIP_I2C1_BR0_ADDR	&UCB1BR0
#define _PERIP_I2C1_BR1_ADDR	&UCB1BR1

#define _PERIP_I2C1_IE_ADDR	&UCB1IE
#define _PERIP_I2C1_IFG_ADDR	&UCB1IFG
#define _PERIP_I2C1_STAT_ADDR	&UCB1STAT


#define _PERIP_I2C1_OA_ADDR &UCB1I2COA
#define _PERIP_I2C1_SA_ADDR &UCB1I2CSA

#define _PERIP_I2C1_RXIE	UCRXIE
#define _PERIP_I2C1_TXIFG	UCTXIFG
#define _PERIP_I2C1_RXIFG	UCRXIFG

#define _PERIP_I2C1_TXBUF_ADDR	&UCB1TXBUF
#define _PERIP_I2C1_RXBUF_ADDR	&UCB1RXBUF

#define _PERIP_I2C1_ISR_VECTOR	USCI_B1_VECTOR


///////////////////timer ////////////////////

#define _PERIP_TIMER_CNT 4

#define _PERIP_TIMER0_CTL_ADDR &TA0CTL
#define _PERIP_TIMER0_CCR0_ADDR &TA0CCR0

#define _PERIP_TIMER0_IE TAIE
#define _PERIP_TIMER0_OV_ISR_VECTOR TIMER0_A1_VECTOR
#define _PERIP_TIMER0_OV_ISR_CALLBACKS_ADDR &TIMER0_A1_ISR_callbacks

#define _PERIP_TIMER1_CTL_ADDR &TA1CTL
#define _PERIP_TIMER1_CCR0_ADDR &TA1CCR0

#define _PERIP_TIMER1_IE TAIE
#define _PERIP_TIMER1_OV_ISR_VECTOR TIMER1_A1_VECTOR
#define _PERIP_TIMER1_OV_ISR_CALLBACKS_ADDR &TIMER1_A1_ISR_callbacks

#define _PERIP_TIMER2_CTL_ADDR &TA2CTL
#define _PERIP_TIMER2_CCR0_ADDR &TA2CCR0

#define _PERIP_TIMER2_IE TAIE
#define _PERIP_TIMER2_OV_ISR_VECTOR TIMER2_A1_VECTOR
#define _PERIP_TIMER2_OV_ISR_CALLBACKS_ADDR &TIMER2_A1_ISR_callbacks

#define _PERIP_TIMER3_CTL_ADDR &TB0CTL
#define _PERIP_TIMER3_CCR0_ADDR &TB0CCR0

#define _PERIP_TIMER3_IE TBIE
#define _PERIP_TIMER3_OV_ISR_VECTOR TIMERB1_VECTOR
#define _PERIP_TIMER3_OV_ISR_CALLBACKS_ADDR &TIMERB1_ISR_callbacks



#endif
