
#ifndef __PERIP_H
#define __PERIP_H

#include <msp430.h>

//#include "hw_obj.h"

//////////////uart////////////////////
#define	_PERIP_UART_CNT	2

#define _PERIP_UART0_XD_PORT_SEL_ADDR	PBSEL_
#define _PERIP_UART0_XD_PORT_SEL2_ADDR	NULL_ADDR

#define _PERIP_UART0_TXD	BIT3
#define _PERIP_UART0_RXD	BIT4


#define _PERIP_UART0_CTL0_ADDR	(addr)(UCA0CTLW0_+1)
#define _PERIP_UART0_CTL1	(addr)(UCA0CTLW0_)
#define _PERIP_UART0_BR0	(UCA0BRW_)
#define _PERIP_UART0_BR1	(UCA0BRW_+1)
#define _PERIP_UART0_MCTL	UCA0MCTL_

#define _PERIP_UART0_IE_ADDR	(UCA0ICTL_)
#define _PERIP_UART0_IFG_ADDR	(UCA0ICTL_+1)

#define _PERIP_UART0_RXIE	UCRXIE
#define _PERIP_UART0_TXIFG	UCTXIFG
#define _PERIP_UART0_RXIFG	UCRXIFG

#define _PERIP_UART0_TXBUF_ADDR	UCA0TXBUF_
#define _PERIP_UART0_RXBUF_ADDR	UCA0RXBUF_

#define _PERIP_UART0_ISR_VECTOR	USCI_A0_VECTOR


#define _PERIP_UART1_XD_PORT_SEL_ADDR	(PBSEL_+1)
#define _PERIP_UART1_XD_PORT_SEL2_ADDR	NULL_ADDR

#define _PERIP_UART1_TXD	BIT4
#define _PERIP_UART1_RXD	BIT5


#define _PERIP_UART1_CTL0_ADDR	(addr)(UCA1CTLW0_+1)
#define _PERIP_UART1_CTL1	(addr)(UCA1CTLW0_)
#define _PERIP_UART1_BR0	(UCA1BRW_)
#define _PERIP_UART1_BR1	(UCA1BRW_+1)
#define _PERIP_UART1_MCTL	UCA1MCTL_

#define _PERIP_UART1_IE_ADDR	(UCA1ICTL_)
#define _PERIP_UART1_IFG_ADDR	(UCA1ICTL_+1)

#define _PERIP_UART1_RXIE	UCRXIE
#define _PERIP_UART1_TXIFG	UCTXIFG
#define _PERIP_UART1_RXIFG	UCRXIFG

#define _PERIP_UART1_TXBUF_ADDR	UCA1TXBUF_
#define _PERIP_UART1_RXBUF_ADDR	UCA1RXBUF_

#define _PERIP_UART1_ISR_VECTOR	USCI_A1_VECTOR



// #define	_PERIP_PWM0_CTL	TACTL_
// #define	_PERIP_PWM0_CCTL0	CCTL0_
// #define	_PERIP_PWM0_CCTL1	CCTL1_
// #define	_PERIP_PWM0_CCTL2	CCTL2_
// 
// #define	_PERIP_PWM0_CCR0	CCR0_
// #define	_PERIP_PWM0_CCR1	CCR1_
// #define	_PERIP_PWM0_CCR2	CCR2_


#endif
