
#ifndef __PERIP_H
#define __PERIP_H

#include <msp430.h>

//////////////uart//////////////////

#define	_PERIP_UART_CNT	1

#define _PERIP_UART0_XD_PORT_SEL_ADDR	P1SEL_
#define _PERIP_UART0_XD_PORT_SEL2_ADDR	P1SEL2_

#define _PERIP_UART0_TXD	BIT1
#define _PERIP_UART0_RXD	BIT2


#define _PERIP_UART0_CTL0_ADDR	(addr)(UCA0CTLW0_+1)
#define _PERIP_UART0_CTL1	(addr)(UCA0CTLW0_)
#define _PERIP_UART0_BR0	(UCA0BRW_)
#define _PERIP_UART0_BR1	(UCA0BRW_+1)
#define _PERIP_UART0_MCTL	UCA0MCTL_

#define _PERIP_UART0_IE_ADDR	(UCA0ICTL_)
#define _PERIP_UART0_IFG_ADDR	(UCA0ICTL_+1)

#define _PERIP_UART0_RXIE	UCRXIE
#define _PERIP_UART0_TXIFG	UCTXIFG
#define _PERIP_UART0_RXIFG	UCRXIFG

#define _PERIP_UART0_TXBUF_ADDR	UCA0TXBUF_
#define _PERIP_UART0_RXBUF_ADDR	UCA0RXBUF_

#define _PERIP_UART0_ISR_VECTOR	USCI_A0_VECTOR

#define _PERIP_UART0_XLED_PORT_DIR_ADDR	P1DIR_
#define _PERIP_UART0_XLED_PORT_OUT_ADDR	P1OUT_

#define _PERIP_UART0_TXLED	BIT0
#define _PERIP_UART0_RXLED	BIT6

#define _PERIP_UART0_RX_ISR	NULL

/////////////pwm/////////////

#define	_PERIP_PWM_CNT	1

#define	_PERIP_PWM0_PORT_SEL_ADDR	P1SEL_
#define	_PERIP_PWM0_PORT_SEL2_ADDR	P1SEL2_
#define	_PERIP_PWM0_PORT_DIR_ADDR	P1DIR_


#define	_PERIP_PWM0_OUT0	5
#define	_PERIP_PWM0_OUTs	BIT1  // Default P1.6 TA0.1 Only
/*
#define	_PERIP_PWM0_OUT0	1
#define	_PERIP_PWM0_OUTs	0x01
*/

#define	_PERIP_PWM0_CTL	TACTL_
#define	_PERIP_PWM0_CCTL0	CCTL0_
#define	_PERIP_PWM0_CCTL1	CCTL1_
#define	_PERIP_PWM0_CCTL2	CCTL2_

#define	_PERIP_PWM0_CCR0	CCR0_
#define	_PERIP_PWM0_CCR1	CCR1_
#define	_PERIP_PWM0_CCR2	CCR2_


#endif
