
#ifndef __PERIP_H
#define __PERIP_H

#include <msp430.h>

//////////////uart//////////////////
#define __BOARD_HAS_UART__

#define	_PERIP_UART_CNT	1

#define _PERIP_UART0_XD_PORT_SEL_ADDR	&P1SEL
#define _PERIP_UART0_XD_PORT_SEL2_ADDR	&P1SEL2

#define _PERIP_UART0_TXD	BIT1
#define _PERIP_UART0_RXD	BIT2

#define _PERIP_UART0_CTL0_ADDR	&UCA0CTL0
#define _PERIP_UART0_CTL1_ADDR	&UCA0CTL1
#define _PERIP_UART0_BR0_ADDR	&UCA0BR0
#define _PERIP_UART0_BR1_ADDR	&UCA0BR1
#define _PERIP_UART0_MCTL_ADDR	&UCA0MCTL

#define _PERIP_UART0_IE_ADDR	&IE2
#define _PERIP_UART0_IFG_ADDR	&IFG2

#define _PERIP_UART0_RXIE	UCA0RXIE
#define _PERIP_UART0_TXIFG	UCA0TXIFG
#define _PERIP_UART0_RXIFG	UCA0RXIFG

#define _PERIP_UART0_TXBUF_ADDR	&UCA0TXBUF
#define _PERIP_UART0_RXBUF_ADDR	&UCA0RXBUF

#define _PERIP_UART0_ISR_VECTOR	USCIAB0RX_VECTOR


/////////////pwm/////////////
#define __BOARD_HAS_PWM__

#define	_PERIP_PWM_CNT	2

#define _PERIP_PWM0_PORT_SEL_ADDR	&P1SEL
#define _PERIP_PWM0_PORT_SEL2_ADDR	&P1SEL2
#define _PERIP_PWM0_PORT_DIR_ADDR	&P1DIR

#define	_PERIP_PWM0_OUT1	6

#define _PERIP_PWM0_CTL_ADDR	&TA0CTL
#define _PERIP_PWM0_CCTL0_ADDR	&TA0CCTL0
#define _PERIP_PWM0_CCTL1_ADDR	&TA0CCTL1
#define _PERIP_PWM0_CCTL2_ADDR	&TA0CCTL2

#define _PERIP_PWM0_CCR0_ADDR	&TA0CCR0
#define _PERIP_PWM0_CCR1_ADDR	&TA0CCR1
#define _PERIP_PWM0_CCR2_ADDR	&TA0CCR2

#define _PERIP_PWM1_PORT_SEL_ADDR	&P2SEL
#define _PERIP_PWM1_PORT_SEL2_ADDR	&P2SEL2
#define _PERIP_PWM1_PORT_DIR_ADDR	&P2DIR

#define	_PERIP_PWM1_OUT1	1

#define _PERIP_PWM1_CTL_ADDR	&TA1CTL
#define _PERIP_PWM1_CCTL0_ADDR	&TA1CCTL0
#define _PERIP_PWM1_CCTL1_ADDR	&TA1CCTL1
#define _PERIP_PWM1_CCTL2_ADDR	&TA1CCTL2

#define _PERIP_PWM1_CCR0_ADDR	&TA1CCR0
#define _PERIP_PWM1_CCR1_ADDR	&TA1CCR1
#define _PERIP_PWM1_CCR2_ADDR	&TA1CCR2


/////////////////i2c//////////////////////
#define __BOARD_HAS_I2C__

#define _PERIP_I2C0_XD_PORT_SEL_ADDR	&P1SEL
#define _PERIP_I2C0_XD_PORT_SEL2_ADDR	&P1SEL2

#define _PERIP_I2C0_SCL	BIT7
#define _PERIP_I2C0_SDA	BIT6


#define _PERIP_I2C0_CTL0_ADDR	&UCB0CTL0
#define _PERIP_I2C0_CTL1_ADDR	&UCB0CTL1
#define _PERIP_I2C0_BR0_ADDR	&UCB0BR0
#define _PERIP_I2C0_BR1_ADDR	&UCB0BR1

#define _PERIP_I2C0_IE_ADDR	&IE2
#define _PERIP_I2C0_IFG_ADDR	&IFG2
#define _PERIP_I2C0_STAT_ADDR	&UCB0STAT


#define _PERIP_I2C0_OA_ADDR &UCB0I2COA
#define _PERIP_I2C0_SA_ADDR &UCB0I2CSA

#define _PERIP_I2C0_RXIE	UCB0RXIE
#define _PERIP_I2C0_TXIFG	UCB0TXIFG
#define _PERIP_I2C0_RXIFG	UCB0RXIFG

#define _PERIP_I2C0_TXBUF_ADDR	&UCB0TXBUF
#define _PERIP_I2C0_RXBUF_ADDR	&UCB0RXBUF

#define _PERIP_I2C0_ISR_VECTOR	USCIAB0RX_VECTOR


///////////////////timer ////////////////////
#define __BOARD_HAS_TIMER__

#define _PERIP_TIMER_CNT 2

const unsigned int TIOV = 10;

#define _PERIP_TIMER0_CTL_ADDR &TA0CTL
#define _PERIP_TIMER0_CCR0_ADDR &TA0CCR0

#define _PERIP_TIMER0_IE TAIE
#define _PERIP_TIMER0_OV_ISR_VECTOR TIMER0_A1_VECTOR
// #define _PERIP_TIMER0_OV_ISR_CALLBACKS_ADDR &TIMER0_A1_ISR_callbacks

#define _PERIP_TIMER1_CTL_ADDR &TA1CTL
#define _PERIP_TIMER1_CCR0_ADDR &TA1CCR0

#define _PERIP_TIMER1_IE TAIE
#define _PERIP_TIMER1_OV_ISR_VECTOR TIMER1_A1_VECTOR
// #define _PERIP_TIMER1_OV_ISR_CALLBACKS_ADDR &TIMER1_A1_ISR_callbacks


#endif
