
#ifndef __CALIB_VAL_H
#define __CALIB_VAL_H


/*DCO quick settings*/
#define BC1MSET {BCSCTL1 = CALBC1_1MHZ; DCOCTL = CALDCO_1MHZ;}
#define BC8MSET {BCSCTL1 = CALBC1_8MHZ; DCOCTL = CALDCO_8MHZ;}
#define BC12MSET {BCSCTL1 = CALBC1_12MHZ; DCOCTL = CALDCO_12MHZ;}
#define BC16MSET {BCSCTL1 = CALBC1_16MHZ; DCOCTL = CALDCO_16MHZ;}


#endif
